/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf8ff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e3dfff",
        "background": "#fbf8ff",
        "tertiary-fixed": "#ffddb9",
        "primary-container": "#2db7f2",
        "on-background": "#1a1b26",
        "inverse-on-surface": "#f1efff",
        "surface-container-high": "#e8e6f6",
        "on-primary-container": "#00455f",
        "on-surface-variant": "#3e484f",
        "primary-fixed-dim": "#7cd0ff",
        "on-error-container": "#93000a",
        "on-surface": "#1a1b26",
        "surface": "#fbf8ff",
        "on-primary": "#ffffff",
        "outline": "#6e7980",
        "on-error": "#ffffff",
        "outline-variant": "#bdc8d1",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed": "#100069",
        "surface-container-highest": "#e3e1f1",
        "on-primary-fixed-variant": "#004c69",
        "secondary-container": "#675df9",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dad8e8",
        "secondary-fixed-dim": "#c4c0ff",
        "inverse-surface": "#2f2f3b",
        "on-primary-fixed": "#001e2c",
        "tertiary": "#865300",
        "on-tertiary-fixed-variant": "#663e00",
        "secondary": "#4d41df",
        "on-tertiary-container": "#5c3700",
        "primary-fixed": "#c4e7ff",
        "inverse-primary": "#7cd0ff",
        "surface-container": "#eeecfc",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3622ca",
        "surface-variant": "#e3e1f1",
        "on-tertiary": "#ffffff",
        "primary": "#00668a",
        "on-tertiary-fixed": "#2b1700",
        "surface-tint": "#00668a",
        "surface-container-low": "#f4f2ff",
        "tertiary-container": "#ec9a26",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb963"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
